// Whitespace
WHITESPACE = _{ " " | "\t" }

// Helpers
not_newline = @{ !NEWLINE ~ ANY }
any_till_nl = @{ not_newline* }

// Sequence Definition
sequence_header = @{ ">" ~ any_till_nl }
sequence_line = @{ (ASCII_ALPHA | "-" | "*")+ }
sequence_multiline = {
	(sequence_line ~ NEWLINE ~ &sequence_line)*
    ~ sequence_line
}

// Singleseq Definition
singleseq_def = {
	sequence_header ~ NEWLINE ~ sequence_multiline
}

// Multiseq Block
multiseq_def = {
	(singleseq_def ~ NEWLINE+ ~ &singleseq_def)*
    ~ singleseq_def
}
fasta = {
	SOI ~ multiseq_def ~ NEWLINE* ~ EOI
}